/* Panel1.java
 * @autor  prof. dr Sinisa Vlajic,
 * Univerzitet u Beogradu
 * Fakultet organizacionih nauka 
 * Katedra za softversko inzenjerstvo
 * Laboratorija za softversko inzenjerstvo
 * 06.11.2017
 */

package AbstractProductA;



import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.GregorianCalendar;


// Promenljivo!!!
public class Panel1 extends Panel{

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrojIndeksa = new javax.swing.JFormattedTextField();
        SifraPredmeta = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SifraPrijave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kreiraj = new javax.swing.JButton();
        Promeni = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        Nadji = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Poruka = new javax.swing.JTextField();
        Datum = new datechooser.beans.DateChooserCombo();
        Ocena = new javax.swing.JComboBox<>();

        try {
            BrojIndeksa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BrojIndeksa.setName("BrojIndeksa"); // NOI18N
        BrojIndeksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BrojIndeksaKeyPressed(evt);
            }
        });

        SifraPredmeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        SifraPredmeta.setDoubleBuffered(true);
        SifraPredmeta.setName("SifraPredmeta"); // NOI18N
        SifraPredmeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraPredmetaKeyPressed(evt);
            }
        });

        jLabel1.setText("Broj indeksa:");

        jLabel2.setText("Sifra predmeta:");

        jLabel3.setText("Ocena:");

        SifraPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifraPrijaveActionPerformed(evt);
            }
        });
        SifraPrijave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraPrijaveKeyPressed(evt);
            }
        });

        jLabel4.setText("Sifra prijave");

        jLabel5.setText("Datum:");

        Kreiraj.setText("Kreiraj");

        Promeni.setText("Promeni");

        Obrisi.setText("Obrisi");

        Nadji.setText("Nadji");
        Nadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NadjiActionPerformed(evt);
            }
        });

        jLabel6.setText("Poruka:");

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });

        Datum.setFormat(2);

        Ocena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BrojIndeksa)
                                    .addComponent(SifraPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SifraPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nadji))
                            .addComponent(Datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Kreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Promeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Obrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Poruka, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SifraPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Nadji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrojIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SifraPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kreiraj)
                    .addComponent(Promeni)
                    .addComponent(Obrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Poruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BrojIndeksaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BrojIndeksaKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraPredmeta.requestFocusInWindow();
          } 
    }//GEN-LAST:event_BrojIndeksaKeyPressed

    private void SifraPredmetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraPredmetaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                Ocena.requestFocusInWindow();
       } // TODO add your handling code here:
    }//GEN-LAST:event_SifraPredmetaKeyPressed

    private void SifraPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifraPrijaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifraPrijaveActionPerformed

    private void NadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NadjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NadjiActionPerformed

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed

    private void SifraPrijaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraPrijaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                BrojIndeksa.requestFocusInWindow();
          }
    }//GEN-LAST:event_SifraPrijaveKeyPressed

          
    @Override   
    public void setSifraPrijave(String SifraPrijave1) {SifraPrijave.setText(SifraPrijave1);}
    @Override   
    public void setSifraPredmeta(String SifraPredmeta1){SifraPredmeta.setText(SifraPredmeta1);}
    @Override   
    public void setBrojIndeksa(String BrojIndeksa1){BrojIndeksa.setText(BrojIndeksa1);}
    @Override   
    public void setOcena(String Ocena1){Ocena.setSelectedItem(Ocena1);}

    /**
     *
     * @param Datum1
     */
    @Override   
    public void setDatum(Date Datum1) 
    {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(Datum1);
        Datum.setSelectedDate(gc);
    } 
    @Override   
    public void setPoruka(String Poruka1) {Poruka.setText(Poruka1);} 
    

    @Override
    public String getSifraPrijave() {return SifraPrijave.getText();}
    @Override
    public String getSifraPredmeta (){return SifraPredmeta.getText();}
    @Override
    public String getBrojIndeksa (){return BrojIndeksa.getText();}
    @Override
    public String getOcena (){return Ocena.getSelectedItem().toString();}
    @Override
    public Date getDatum() {return Datum.getSelectedDate().getTime();}
    
     @Override
    public javax.swing.JButton getKreiraj(){return Kreiraj;}
     @Override
    public javax.swing.JButton getPromeni(){return Promeni;}
     @Override
    public javax.swing.JButton getObrisi(){return Obrisi;}
     @Override
    public javax.swing.JButton getNadji(){return Nadji;}
     @Override
    public javax.swing.JTextField getSifraPrijave1(){return SifraPrijave;}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BrojIndeksa;
    private datechooser.beans.DateChooserCombo Datum;
    private javax.swing.JButton Kreiraj;
    private javax.swing.JButton Nadji;
    private javax.swing.JButton Obrisi;
    private javax.swing.JComboBox<String> Ocena;
    private javax.swing.JTextField Poruka;
    private javax.swing.JButton Promeni;
    private javax.swing.JFormattedTextField SifraPredmeta;
    private javax.swing.JTextField SifraPrijave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
