/* Panel2.java
 * @autor  prof. dr Sinisa Vlajic,
 * Univerzitet u Beogradu
 * Fakultet organizacionih nauka 
 * Katedra za softversko inzenjerstvo
 * Laboratorija za softversko inzenjerstvo
 * 06.11.2017
 */

package AbstractProductA;



import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.GregorianCalendar;

// Promenljivo!!!
public class Panel2 extends Panel{

    /**
     * Creates new form Panel1
     */
    public Panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrojIndeksa = new javax.swing.JFormattedTextField();
        SifraPredmeta = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SifraPrijave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kreiraj = new javax.swing.JButton();
        Promeni = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        Nadji = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Poruka = new javax.swing.JTextField();
        Datum = new datechooser.beans.DateChooserCombo();
        Ocena = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            BrojIndeksa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BrojIndeksa.setName("BrojIndeksa"); // NOI18N
        BrojIndeksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BrojIndeksaKeyPressed(evt);
            }
        });
        add(BrojIndeksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 54, -1));

        SifraPredmeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        SifraPredmeta.setDoubleBuffered(true);
        SifraPredmeta.setName("SifraPredmeta"); // NOI18N
        SifraPredmeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraPredmetaKeyPressed(evt);
            }
        });
        add(SifraPredmeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 36, -1));

        jLabel1.setText("Broj indeksa:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setText("Sifra predmeta:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Ocena:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        SifraPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifraPrijaveActionPerformed(evt);
            }
        });
        SifraPrijave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraPrijaveKeyPressed(evt);
            }
        });
        add(SifraPrijave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 54, -1));

        jLabel4.setText("Sifra prijave");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Datum:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Kreiraj.setText("Kreiraj");
        add(Kreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        Promeni.setText("Promeni");
        add(Promeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        Obrisi.setText("Obrisi");
        add(Obrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Nadji.setText("Nadji");
        Nadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NadjiActionPerformed(evt);
            }
        });
        add(Nadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setText("Poruka:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 211, 45, -1));

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });
        add(Poruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 208, 250, -1));

        Datum.setFormat(1);
        add(Datum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        Ocena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10" }));
        add(Ocena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AkreditacijaSILAB.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void BrojIndeksaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BrojIndeksaKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraPredmeta.requestFocusInWindow();
          } 
    }//GEN-LAST:event_BrojIndeksaKeyPressed

    private void SifraPredmetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraPredmetaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                Ocena.requestFocusInWindow();
       } // TODO add your handling code here:
    }//GEN-LAST:event_SifraPredmetaKeyPressed

    private void SifraPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifraPrijaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifraPrijaveActionPerformed

    private void NadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NadjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NadjiActionPerformed

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed

    private void SifraPrijaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraPrijaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                BrojIndeksa.requestFocusInWindow();
          }
    }//GEN-LAST:event_SifraPrijaveKeyPressed

       
    @Override   
    public void setSifraPrijave(String SifraPrijave1) {SifraPrijave.setText(SifraPrijave1);}
    @Override   
    public void setSifraPredmeta(String SifraPredmeta1){SifraPredmeta.setText(SifraPredmeta1);}
    @Override   
    public void setBrojIndeksa(String BrojIndeksa1){BrojIndeksa.setText(BrojIndeksa1);}
    @Override   
    public void setOcena(String Ocena1){Ocena.setSelectedItem(Ocena1);}

    /**
     *
     * @param Datum1
     */
    @Override   
    public void setDatum(Date Datum1) 
    {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(Datum1);
        Datum.setSelectedDate(gc);
    } 
    @Override   
    public void setPoruka(String Poruka1) {Poruka.setText(Poruka1);} 
    

    @Override
    public String getSifraPrijave() {return SifraPrijave.getText();}
    @Override
    public String getSifraPredmeta (){return SifraPredmeta.getText();}
    @Override
    public String getBrojIndeksa (){return BrojIndeksa.getText();}
    @Override
    public String getOcena (){return Ocena.getSelectedItem().toString();}
    @Override
    public Date getDatum() {return Datum.getSelectedDate().getTime();}
    
     @Override
    public javax.swing.JButton getKreiraj(){return Kreiraj;}
     @Override
    public javax.swing.JButton getPromeni(){return Promeni;}
     @Override
    public javax.swing.JButton getObrisi(){return Obrisi;}
     @Override
    public javax.swing.JButton getNadji(){return Nadji;}
     @Override
    public javax.swing.JTextField getSifraPrijave1(){return SifraPrijave;}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BrojIndeksa;
    private datechooser.beans.DateChooserCombo Datum;
    private javax.swing.JButton Kreiraj;
    private javax.swing.JButton Nadji;
    private javax.swing.JButton Obrisi;
    private javax.swing.JComboBox<String> Ocena;
    private javax.swing.JTextField Poruka;
    private javax.swing.JButton Promeni;
    private javax.swing.JFormattedTextField SifraPredmeta;
    private javax.swing.JTextField SifraPrijave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
